---
- name: Skip tags
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - debug:
        msg: "Message 1"
      tags:
        - tag1

    - debug:
        msg: "Message 2"
      tags:
        - tag2

    - debug:
        msg: "This should be the only displayed message"
